[build]
build-std = false # do not build the std library. has precedence over xargo
xargo = false     # disable the use of xargo by default
zig = false       # do not use zig cc for the builds

[target.aarch64-unknown-linux-gnu]
image = "rust:1.86-bullseye"
pre-build = [ # additional commands to run prior to building the package
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get --assume-yes install libssl-dev:$CROSS_DEB_ARCH",
    # "export MINGW_PREFIX=/usr/x86_64-w64-mingw32/lib",
]
